---
  title: "R Description"
author: "j"
date: "25/1/2021"
output: html_document
---
*factor* permite crear datos categoricos.
```{r factor1, echo = TRUE}
x <- factor(c("LUNES","MARTES","LUNES", "LUNES"))
print(x)
```
# 1.- factor attributes

```{r factor2, echo = TRUE}
x <- factor(c("LUNES","MARTES","LUNES", "LUNES"), levels = c("LUNES", "MARTES"))
print(x)
```
categorizados por R:

```{r table, echo = TRUE}
table(x)
```

## Attributes levels
Get numeric distinctions:
```{r unclass, echo=TRUE}
unclass(x)
```
or get attributes:
```{r attributes, echo= FALSE}
attr(x,"levels")
```

# 2. Matrices

## crear una matriz
```{r matriz}
m = 1:12
#reshape
dim(m) <-c(3,4)
print(m)
```

# 3. writing data
```{r dput}
dput(x, file = "Data.R")
```


## Data frames
se pueden crear **data frames** con matrices:
  
  ```{r a_mat, echo = TRUE}
df <- data.frame(a_mat)
print(df)
```

## Change attributes names

```{r attributes, echo=TRUE}
attributes(df)$names <- c("VAR1","VAR2","VAR3")
print(df)
```
o
```{r names, echo = FALSE}
names(df)<- c("I1","I2", "I3")
```

